# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 16:42
from __future__ import unicode_literals

import category.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=category.models.uplaod_location, width_field='width_field')),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('descriptions', models.TextField()),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Menu')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
